# Generated by Django 6.0.4 on 2026-04-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "end_reading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("reading_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("th", models.IntegerField(blank=True, null=True)),
                ("cv", models.IntegerField(blank=True, null=True)),
                ("rm", models.IntegerField(blank=True, null=True)),
                ("ex", models.IntegerField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_points",
                        to="subject.subject",
                    ),
                ),
            ],
        ),
    ]

