# Generated by Django 6.0.4 on 2026-04-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('break_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='breakpoint',
            table='break_point_break_points',
        ),
    ]
