# Generated by Django 6.0.4 on 2026-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('break_point', '0002_alter_breakpoint_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakpoint',
            name='end_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
