# Generated by Django 6.0.4 on 2026-04-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('break_point', '0003_alter_breakpoint_end_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakpoint',
            name='status',
        ),
    ]
