# Generated by Django 6.0.4 on 2026-04-24 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('break_point', '0004_remove_breakpoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='cv',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='end_reading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='ex',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='reading_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='rm',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='th',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
