# Generated by Django 6.0.4 on 2026-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('break_point', '0005_breakpoint_description_alter_breakpoint_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakpoint',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='end_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakpoint',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
