# Generated by Django 6.0.4 on 2026-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='current_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
