# Generated by Django 6.0.4 on 2026-04-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_current_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='mode',
        ),
    ]
