# Generated by Django 6.0.4 on 2026-04-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='current_reading',
            new_name='category_current_reading',
        ),
    ]
