# Generated by Django 6.0.4 on 2026-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_current_reading_category_category_current_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_current_reading',
            field=models.IntegerField(default=0),
        ),
    ]
