# Generated by Django 6.0.4 on 2026-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_category_current_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_current_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
