# Generated by Django 6.0.4 on 2026-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_category_current_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_current_reading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=2),
        ),
    ]
