# Generated by Django 6.0.4 on 2026-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
