# Generated by Django 6.0.4 on 2026-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='last_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_end_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mode',
            field=models.CharField(default='date_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
