# Generated by Django 6.0.4 on 2026-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_last_end_date_subject_last_end_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='last_end_reading',
            field=models.IntegerField(default=0),
        ),
    ]
