# Generated by Django 6.0.4 on 2026-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_subject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='last_end_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
