# Generated by Django 6.0.4 on 2026-04-24 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_alter_subject_last_end_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='last_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_end_reading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
