# Generated by Django 6.0.4 on 2026-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_alter_subject_last_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='last_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_end_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
